services:
  gemona_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gemona_api
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=${MYSQL_CONNECTION_STRING}
      - JwtSettings__SecretKey=${JWT_SECRET_KEY}
      - JwtSettings__Issuer=GemonaAPI
      - JwtSettings__Audience=GemonaClients
      - JwtSettings__ExpiresInDays=7
      - AzureStorage__ConnectionString=${AZURE_STORAGE_CONNECTION_STRING}
      - AzureStorage__ContainerName=images
      - OpenCage__ApiKey=${OPENCAGE_API_KEY}
    ports:
      - "5268:8080"
    networks:
      - gemona_network

networks:
  gemona_network:
    driver: bridge
